<a href="https://colab.research.google.com/github/Krishna-matic/python_practice/blob/main/Adult_Income_Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [6]:
df = pd.read_csv('/content/drive/MyDrive/DataSetForpython/adult.csv',na_values="?")
df.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,NaN,103497,Some-college,10,Never-married,NaN,Own-child,White,Female,0,0,30,United-States,<=50K

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              48842 non-null  int64
 1   workclass        46043 non-null  object
 2   fnlwgt           48842 non-null  int64
 3   education        48842 non-null  object
 4   educational-num  48842 non-null  int64
 5   marital-status   48842 non-null  object
 6   occupation       46033 non-null  object
 7   relationship     48842 non-null  object
 8   race             48842 non-null  object
 9   gender           48842 non-null  object
 10  capital-gain     48842 non-null  int64
 11  capital-loss     48842 non-null  int64
 12  hours-per-week   48842 non-null  int64
 13  native-country   47985 non-null  object
 14  income           48842 non-null  object
dtypes: int64(6), object(9)
memory usage: 5.6+ MB

In [8]:
df.duplicated().sum()

np.int64(52)

In [9]:
df.isnull().sum()

age                   0
workclass          2799
fnlwgt                0
education             0
educational-num       0
marital-status        0
occupation         2809
relationship          0
race                  0
gender                0
capital-gain          0
capital-loss          0
hours-per-week        0
native-country      857
income                0
dtype: int64

In [10]:
for col in df.select_dtypes(include='object').columns:
    print(col)
    print(df[col].unique())
    print("-"*50)

workclass
['Private' 'Local-gov' nan 'Self-emp-not-inc' 'Federal-gov' 'State-gov'
 'Self-emp-inc' 'Without-pay' 'Never-worked']
--------------------------------------------------
education
['11th' 'HS-grad' 'Assoc-acdm' 'Some-college' '10th' 'Prof-school'
 '7th-8th' 'Bachelors' 'Masters' 'Doctorate' '5th-6th' 'Assoc-voc' '9th'
 '12th' '1st-4th' 'Preschool']
--------------------------------------------------
marital-status
['Never-married' 'Married-civ-spouse' 'Widowed' 'Divorced' 'Separated'
 'Married-spouse-absent' 'Married-AF-spouse']
--------------------------------------------------
occupation
['Machine-op-inspct' 'Farming-fishing' 'Protective-serv' nan
 'Other-service' 'Prof-specialty' 'Craft-repair' 'Adm-clerical'
 'Exec-managerial' 'Tech-support' 'Sales' 'Priv-house-serv'
 'Transport-moving' 'Handlers-cleaners' 'Armed-Forces']
--------------------------------------------------
relationship
['Own-child' 'Husband' 'Not-in-family' 'Unmarried' 'Wife' 'Other-relative']
--------------------------------------------------
race
['Black' 'White' 'Asian-Pac-Islander' 'Other' 'Amer-Indian-Eskimo']
--------------------------------------------------
gender
['Male' 'Female']
--------------------------------------------------
native-country
['United-States' nan 'Peru' 'Guatemala' 'Mexico' 'Dominican-Republic'
 'Ireland' 'Germany' 'Philippines' 'Thailand' 'Haiti' 'El-Salvador'
 'Puerto-Rico' 'Vietnam' 'South' 'Columbia' 'Japan' 'India' 'Cambodia'
 'Poland' 'Laos' 'England' 'Cuba' 'Taiwan' 'Italy' 'Canada' 'Portugal'
 'China' 'Nicaragua' 'Honduras' 'Iran' 'Scotland' 'Jamaica' 'Ecuador'
 'Yugoslavia' 'Hungary' 'Hong' 'Greece' 'Trinadad&Tobago'
 'Outlying-US(Guam-USVI-etc)' 'France' 'Holand-Netherlands']
--------------------------------------------------
income
['<=50K' '>50K']
--------------------------------------------------

In [11]:
# Percentage of missing values in each column
missing_percentage = (df.isnull().sum() / len(df)) * 100
# Show only columns with missing values
missing_percentage = missing_percentage[missing_percentage > 0]
print(missing_percentage)

workclass         5.730724
occupation        5.751198
native-country    1.754637
dtype: float64

In [12]:
for col in ['workclass', 'occupation', 'native-country']:
    print(f"\n{col}")
    print(df[col].value_counts().head())

workclass
workclass
Private             33906
Self-emp-not-inc     3862
Local-gov            3136
State-gov            1981
Self-emp-inc         1695
Name: count, dtype: int64

occupation
occupation
Prof-specialty     6172
Craft-repair       6112
Exec-managerial    6086
Adm-clerical       5611
Sales              5504
Name: count, dtype: int64

native-country
native-country
United-States    43832
Mexico             951
Philippines        295
Germany            206
Puerto-Rico        184
Name: count, dtype: int64

In [13]:
for col in ['workclass', 'occupation', 'native-country']:
    df[col].fillna(df[col].mode()[0], inplace=True)

/tmp/ipykernel_1803/1643398779.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

In [14]:
df.isnull().sum()

age                0
workclass          0
fnlwgt             0
education          0
educational-num    0
marital-status     0
occupation         0
relationship       0
race               0
gender             0
capital-gain       0
capital-loss       0
hours-per-week     0
native-country     0
income             0
dtype: int64

In [15]:
duplicates = df.duplicated().sum()
print(f"Number of duplicate rows: {duplicates}")

Number of duplicate rows: 53

In [16]:
df = df.drop_duplicates()

In [18]:
df.shape

(48789, 15)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 48789 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              48789 non-null  int64
 1   workclass        48789 non-null  object
 2   fnlwgt           48789 non-null  int64
 3   education        48789 non-null  object
 4   educational-num  48789 non-null  int64
 5   marital-status   48789 non-null  object
 6   occupation       48789 non-null  object
 7   relationship     48789 non-null  object
 8   race             48789 non-null  object
 9   gender           48789 non-null  object
 10  capital-gain     48789 non-null  int64
 11  capital-loss     48789 non-null  int64
 12  hours-per-week   48789 non-null  int64
 13  native-country   48789 non-null  object
 14  income           48789 non-null  object
dtypes: int64(6), object(9)
memory usage: 6.0+ MB

In [21]:
df["workclass"].value_counts()

workclass
Private             36654
Self-emp-not-inc     3861
Local-gov            3136
State-gov            1981
Self-emp-inc         1694
Federal-gov          1432
Without-pay            21
Never-worked           10
Name: count, dtype: int64

In [22]:
df['income'] = df['income'].map({
    '<=50K': 0,
    '>50K': 1
})

In [23]:
categorical_cols = [
    'workclass',
    'education',
    'marital-status',
    'occupation',
    'relationship',
    'race',
    'gender',
    'native-country'
]

df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 48789 entries, 0 to 48841
Data columns (total 98 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   age                                        48789 non-null  int64
 1   fnlwgt                                     48789 non-null  int64
 2   educational-num                            48789 non-null  int64
 3   capital-gain                               48789 non-null  int64
 4   capital-loss                               48789 non-null  int64
 5   hours-per-week                             48789 non-null  int64
 6   income                                     48789 non-null  int64
 7   workclass_Local-gov                        48789 non-null  bool
 8   workclass_Never-worked                     48789 non-null  bool
 9   workclass_Private                          48789 non-null  bool
 10  workclass_Self-emp-inc                     48789 non-null  bool
 11  workclass_Self-emp-not-inc                 48789 non-null  bool
 12  workclass_State-gov                        48789 non-null  bool
 13  workclass_Without-pay                      48789 non-null  bool
 14  education_11th                             48789 non-null  bool
 15  education_12th                             48789 non-null  bool
 16  education_1st-4th                          48789 non-null  bool
 17  education_5th-6th                          48789 non-null  bool
 18  education_7th-8th                          48789 non-null  bool
 19  education_9th                              48789 non-null  bool
 20  education_Assoc-acdm                       48789 non-null  bool
 21  education_Assoc-voc                        48789 non-null  bool
 22  education_Bachelors                        48789 non-null  bool
 23  education_Doctorate                        48789 non-null  bool
 24  education_HS-grad                          48789 non-null  bool
 25  education_Masters                          48789 non-null  bool
 26  education_Preschool                        48789 non-null  bool
 27  education_Prof-school                      48789 non-null  bool
 28  education_Some-college                     48789 non-null  bool
 29  marital-status_Married-AF-spouse           48789 non-null  bool
 30  marital-status_Married-civ-spouse          48789 non-null  bool
 31  marital-status_Married-spouse-absent       48789 non-null  bool
 32  marital-status_Never-married               48789 non-null  bool
 33  marital-status_Separated                   48789 non-null  bool
 34  marital-status_Widowed                     48789 non-null  bool
 35  occupation_Armed-Forces                    48789 non-null  bool
 36  occupation_Craft-repair                    48789 non-null  bool
 37  occupation_Exec-managerial                 48789 non-null  bool
 38  occupation_Farming-fishing                 48789 non-null  bool
 39  occupation_Handlers-cleaners               48789 non-null  bool
 40  occupation_Machine-op-inspct               48789 non-null  bool
 41  occupation_Other-service                   48789 non-null  bool
 42  occupation_Priv-house-serv                 48789 non-null  bool
 43  occupation_Prof-specialty                  48789 non-null  bool
 44  occupation_Protective-serv                 48789 non-null  bool
 45  occupation_Sales                           48789 non-null  bool
 46  occupation_Tech-support                    48789 non-null  bool
 47  occupation_Transport-moving                48789 non-null  bool
 48  relationship_Not-in-family                 48789 non-null  bool
 49  relationship_Other-relative                48789 non-null  bool
 50  relationship_Own-child                     48789 non-null  bool
 51  relationship_Unmarried                     48789 non-null  bool
 52  relationship_Wife                          48789 non-null  bool
 53  race_Asian-Pac-Islander                    48789 non-null  bool
 54  race_Black                                 48789 non-null  bool
 55  race_Other                                 48789 non-null  bool
 56  race_White                                 48789 non-null  bool
 57  gender_Male                                48789 non-null  bool
 58  native-country_Canada                      48789 non-null  bool
 59  native-country_China                       48789 non-null  bool
 60  native-country_Columbia                    48789 non-null  bool
 61  native-country_Cuba                        48789 non-null  bool
 62  native-country_Dominican-Republic          48789 non-null  bool
 63  native-country_Ecuador                     48789 non-null  bool
 64  native-country_El-Salvador                 48789 non-null  bool
 65  native-country_England                     48789 non-null  bool
 66  native-country_France                      48789 non-null  bool
 67  native-country_Germany                     48789 non-null  bool
 68  native-country_Greece                      48789 non-null  bool
 69  native-country_Guatemala                   48789 non-null  bool
 70  native-country_Haiti                       48789 non-null  bool
 71  native-country_Holand-Netherlands          48789 non-null  bool
 72  native-country_Honduras                    48789 non-null  bool
 73  native-country_Hong                        48789 non-null  bool
 74  native-country_Hungary                     48789 non-null  bool
 75  native-country_India                       48789 non-null  bool
 76  native-country_Iran                        48789 non-null  bool
 77  native-country_Ireland                     48789 non-null  bool
 78  native-country_Italy                       48789 non-null  bool
 79  native-country_Jamaica                     48789 non-null  bool
 80  native-country_Japan                       48789 non-null  bool
 81  native-country_Laos                        48789 non-null  bool
 82  native-country_Mexico                      48789 non-null  bool
 83  native-country_Nicaragua                   48789 non-null  bool
 84  native-country_Outlying-US(Guam-USVI-etc)  48789 non-null  bool
 85  native-country_Peru                        48789 non-null  bool
 86  native-country_Philippines                 48789 non-null  bool
 87  native-country_Poland                      48789 non-null  bool
 88  native-country_Portugal                    48789 non-null  bool
 89  native-country_Puerto-Rico                 48789 non-null  bool
 90  native-country_Scotland                    48789 non-null  bool
 91  native-country_South                       48789 non-null  bool
 92  native-country_Taiwan                      48789 non-null  bool
 93  native-country_Thailand                    48789 non-null  bool
 94  native-country_Trinadad&Tobago             48789 non-null  bool
 95  native-country_United-States               48789 non-null  bool
 96  native-country_Vietnam                     48789 non-null  bool
 97  native-country_Yugoslavia                  48789 non-null  bool
dtypes: bool(91), int64(7)
memory usage: 7.2 MB

In [26]:
df.drop(columns=['educational-num'], inplace=True)

In [27]:
from sklearn.model_selection import train_test_split
X = df.drop('income', axis=1)
y = df['income']
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [30]:
from sklearn.preprocessing import StandardScaler

numerical_cols = [
    'age',
    'fnlwgt',
    'capital-gain',
    'capital-loss',
    'hours-per-week'
]

scaler = StandardScaler()

X_train_scaled = X_train.copy()
X_test_scaled = X_test.copy()

X_train_scaled[numerical_cols] = scaler.fit_transform(X_train[numerical_cols])
X_test_scaled[numerical_cols] = scaler.transform(X_test[numerical_cols])

In [31]:
print("X_train shape:", X_train.shape)
print("X_test shape :", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape :", y_test.shape)

X_train shape: (39031, 96)
X_test shape : (9758, 96)
y_train shape: (39031,)
y_test shape : (9758,)

In [32]:
from sklearn.linear_model import LogisticRegression
# Create the model
lr = LogisticRegression(random_state=42, max_iter=1000)
# Train the model
lr.fit(X_train_scaled, y_train)

LogisticRegression(max_iter=1000, random_state=42)

In [33]:
y_pred = lr.predict(X_test_scaled)

In [34]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall   :", recall_score(y_test, y_pred))
print("F1 Score :", f1_score(y_test, y_pred))

Accuracy : 0.8482270957163354
Precision: 0.7239392352016762
Recall   : 0.5916095890410958
F1 Score : 0.6511189634864547

Confusion Matrix
[[6895  527]
 [ 954 1382]]

Classification Report
              precision    recall  f1-score   support

           0       0.88      0.93      0.90      7422
           1       0.72      0.59      0.65      2336

    accuracy                           0.85      9758
   macro avg       0.80      0.76      0.78      9758
weighted avg       0.84      0.85      0.84      9758

In [35]:
print("\nConfusion Matrix")
print(confusion_matrix(y_test, y_pred))

Confusion Matrix
[[6895  527]
 [ 954 1382]]

In [36]:
print("\nClassification Report")
print(classification_report(y_test, y_pred))

Classification Report
              precision    recall  f1-score   support

           0       0.88      0.93      0.90      7422
           1       0.72      0.59      0.65      2336

    accuracy                           0.85      9758
   macro avg       0.80      0.76      0.78      9758
weighted avg       0.84      0.85      0.84      9758